- id: auto01
  alias: Update Available Notification
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
  - service: notify.pushbullet
    data:
      message: HomeAssistant {{ states('updater.updater') }} is now available
      title: Update HASS
- id: auto02
  alias: Lounge lights on in the evening
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
  action:
    service: switch.turn_on
    entity_id: switch.lounge_lights
- id: auto03
  alias: Random - Lounge Lights Off
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: group.family
    state: not_home
  action:
  - delay: '{{ ((range(0, 1) | random) | int) ~ ":" ~ ((range(5, 55) | random) | int)  ~
      ":" ~  ((range(5, 55) | random) | int) }}'
- id: auto04
  alias: Reset lights automation
  trigger:
    platform: time
    at: 07:15:00
  action:
    service: automation.turn_on
    entity_id: automation.lounge_lights_on_in_the_evening
- id: auto05
  alias: Wake Me Up
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state
      }}'
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.alarmweekday
      state: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: Alarm_Trigger
      value1: Morning!
  - service: switch.turn_on
    entity_id: switch.master_bedroom_light
- id: auto06
  alias: House Heating On
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.heat_on_time.state
      }}'
  - platform: state
    entity_id: switch.house_heating
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.house_weekday
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.house_weekday
      state: 'off'
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.house
      temperature: 18.0
  - service: automation.turn_on
    entity_id: automation.heating_off_out_of_zone
- id: auto07
  alias: House Heating Off
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.heat_off_time.state
      }}'
  - platform: state
    entity_id: switch.house_heating
    to: 'off'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.house_weekday
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.house_weekday
      state: 'off'
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.house
      temperature: 13
  - service: automation.turn_off
    entity_id: automation.heating_off_out_of_zone
- id: auto08
  alias: Hutch Heating On
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.hutch_on_time.state
      }}'
  - platform: state
    entity_id: switch.hutch_heating
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.hutch_weekday
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.hutch_weekday
      state: 'off'
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.hutch
      temperature: 18.5
- id: auto09
  alias: Hutch Heating Off
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.hutch_off_time.state
      }}'
  - platform: state
    entity_id: switch.hutch_heating
    to: 'off'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.hutch_weekday
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.hutch_weekday
      state: 'off'
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.hutch
      temperature: 1
- id: auto10
  alias: Morning Lounge Lights Off
  trigger:
  - event: sunrise
    offset: 01:00:00
    platform: sun
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.lounge_lights
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.lounge_lights
      state: 'off'
  action:
  - entity_id: switch.lounge_lights
    service: switch.turn_off
- id: auto11
  alias: Morning Lounge Lights On
  trigger:
  - platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.lounge_lights_on_time.state
      }}'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.lounge_lights
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.lounge_lights
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.lounge_lights
- id: auto12
  alias: Benjamin XBox Monitor
  initial_state: 'off'
  trigger:
  - platform: template
    value_template: '{{ states.sensor.benjamin_xbox == "Offline" }}'
  action:
  - delay: 00:05:00
  - service: switch.turn_off
    entity_id: switch.tv
  - service: scene.turn_on
    entity_id: scene.bedtime
- id: auto13
  alias: Heating Off out of Zone
  initial_state: 'off'
  trigger:
  - platform: template
    value_template: '{{ states.group.family == "not_home" }}'
  condition:
  - condition: state
    entity_id: switch.house_heating
    state: 'on'
  action:
  - entity_id: switch.house_heating
    service: switch.turn_off
