homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

frontend:
logger:
  logs:
    homeassistant.components.mqtt: debug

config:

http:
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/hass227.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/hass227.duckdns.org/privkey.pem
  trusted_networks:
    - 10.44.3.0/24

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Database housekeeping
recorder:
  purge_days: 8

# Track the sun
sun:

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 60

sensor: !include_dir_merge_list devices/sensors
switch: !include_dir_merge_list devices/switches
automation: !include automations.yaml
scene: !include scenes.yaml
#binary_sensor: !include binary_sensor.yaml

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:home

zone 2:
  name: UCEA
  latitude: 53.276379
  longitude:  -2.907707
  radius: 100
  icon: mdi:school

zone 3:
  name: Gym
  latitude: 53.263738
  longitude: -2.891398
  radius: 100
  icon: mdi:run

zone 4:
  name: Work
  latitude: 53.347792
  longitude: -2.878179
  radius: 100
  icon: mdi:briefcase

zone 5:
  name: Lodge
  latitude: 52.867931
  longitude: -3.908915
  radius: 100
  icon: mdi:home
  
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pb_api

input_slider:
  house_heat_on_hr:
    name: 'Heat On Hour'
    min: 00
    max: 23
    initial: 06
    step: 1
    icon: mdi:clock
    unit_of_measurement: 'Hours'

  house_heat_on_min:
    name: 'Heat On Min'
    min: 00
    max: 45
    initial: 00
    step: 15
    icon: mdi:clock
    unit_of_measurement: 'Min'

  house_heat_off_hr:
    name: 'Heat Off Hour'
    min: 00
    max: 23
    initial: 06
    step: 1
    icon: mdi:clock
    unit_of_measurement: 'Hours'

  house_heat_off_min:
    name: 'Heat Off Min'
    min: 00
    max: 45
    initial: 00
    step: 15
    icon: mdi:clock
    unit_of_measurement: 'Min'

input_select:
  heating_thermostat_state:
    name: 'House Thermostat Away Mode'
    options:
      - 'On'
      - 'Off'
    icon: mdi:target
  hutch_thermostat_state:
    name: 'Hutch Thermostat Away Mode'
    options:
      - 'On'
      - 'Off'
    icon: mdi:target

device_tracker:
  - platform: owntracks
  - platform: nmap_tracker
    hosts: 10.44.3.0/24
    scan_options: " --privileged -sP"
    home_interval: 10
  - platform: ping
    hosts:
      admonitrix: 10.44.3.15
    count: 3

group: !include groups.yaml

google:
  client_id: !secret g_client_id
  client_secret: !secret g_client_secret

script:
  example_script:
    sequence:
      - service: device_tracker.see
        entity_id: device_tracker.18fe34dabbd5

#media_player:
# - platform: kodi
#    name: Hutch kodi
#    host: 10.44.3.223

climate:
  - platform: generic_thermostat
    name: House
    heater: switch.heating_switch
    target_sensor: sensor.hallway
    min_temp: 13
    max_temp: 21
    target_temp: 18.5
    tolerance: 0.3
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: Hutch
    heater: switch.hutch_heater
    target_sensor: sensor.hutch
    min_temp: 1
    max_temp: 21
    target_temp: 18.5
    tolerance: 0.3
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

android_ip_webcam:
  - host: 10.44.3.225:8081
    scan_interval: 120
    name: 'Camera 1'
    username: 'admin'
    password: !secret camera_pw
    switches:
      - focus
    sensors:
      - battery_level
    motion_sensor: true
