homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: Europe/London
  customize: !include int_customize.yaml

frontend:
logger:
  logs:
    homeassistant.components.mqtt: debug

config:

http:
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/hass227.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/hass227.duckdns.org/privkey.pem
  trusted_networks:
    - 10.44.3.0/24

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Database housekeeping
recorder:
  purge_days: 3
  exclude:
    domains:
      - sun


# Track the sun
sun:

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 60

sensor: !include_dir_merge_list devices/sensors
switch: !include_dir_merge_list devices/switches
automation: !include automations.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_slider: !include input_slider.yaml
alert: !include alert.yaml

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:home

zone 2:
  name: UCEA
  latitude: 53.277080 
  longitude: -2.906817
  radius: 100
  icon: mdi:school

zone 3:
  name: Gym
  latitude: 53.263738
  longitude: -2.891398
  radius: 100
  icon: mdi:run

zone 4:
  name: Work
  latitude: 53.347792
  longitude: -2.878179
  radius: 100
  icon: mdi:briefcase

zone 5:
  name: Lodge
  latitude: 52.867931
  longitude: -3.908915
  radius: 100
  icon: mdi:home

zone 6:
  name: 'Cambridge Road School'
  latitude: 53.279321
  longitude: -2.895744
  radius: 50
  icon: mdi:school
  
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pb_api

  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_sender_key
    gcm_sender_id: !secret gcm-sender-id

device_tracker:
  - platform: owntracks
  - platform: nmap_tracker
    hosts: 10.44.3.0/24
    scan_options: " --privileged -sP"
    home_interval: 10
  - platform: ping
    hosts:
      admonitrix: 10.44.3.15
    count: 3

group: !include groups.yaml

ifttt:
  key: !secret ifttt_key

script:
  example_script:
    sequence:
      - service: device_tracker.see
        entity_id: device_tracker.18fe34dabbd5

climate:
  - platform: generic_thermostat
    name: House
    heater: switch.heating_switch
    target_sensor: sensor.hallway
    min_temp: 13
    max_temp: 21
    target_temp: 13
    tolerance: 0.3
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: Hutch
    heater: switch.hutch_heater
    target_sensor: sensor.hutch
    min_temp: 1
    max_temp: 21
    target_temp: 1
    tolerance: 0.3
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

android_ip_webcam:
  - host: 10.44.3.120
    port: 2271
    scan_interval: 1
    name: 'Lounge'
    username: 'hass227'
    password: !secret camera_pw
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
    sensors:
      - battery_level
      - motion
      - light
  - host: 10.44.3.119
    port: 2271
    scan_interval: 1
    name: 'Hall'
    username: 'hass227'
    password: !secret camera_pw
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
    sensors:
      - battery_level
      - motion
      - light

  - host: 10.44.3.127
    port: 2271
    scan_interval: 1
    name: 'Hutch'
    username: 'hass227'
    password: !secret camera_pw
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
    sensors:
      - battery_level
      - motion
      - light

apiai:
intent_script: !include intent_script.yaml

