- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'
#
# House Heating
#
- platform: template
  sensors:
    heat_on_time:
      friendly_name: 'Heating On'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.heat_on_hour") | int, states("input_number.heat_on_minutes") | int) }}'

- platform: template
  sensors:
    heat_off_time:
      friendly_name: 'Heating Off'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.heat_off_hour") | int, states("input_number.heat_off_minutes") | int) }}'
#
# Hutch Heating
#
- platform: template
  sensors:
    hutch_on_time:
      friendly_name: 'Heating On'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.hutch_on_hour") | int, states("input_number.hutch_on_minutes") | int) }}'

- platform: template
  sensors:
    hutch_off_time:
      friendly_name: 'Heating Off'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.hutch_off_hour") | int, states("input_number.hutch_off_minutes") | int) }}'
#
# Lounge Lights On
#
- platform: template
  sensors:
    lounge_lights_on_time:
      friendly_name: 'lounge Lights On Time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.lounge_lights_on_hour") | int, states("input_number.lounge_lights_on_minutes") | int) }}'