- alias: 'Lounge lights on in the evening'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:15:00'
  condition:
    # Prefix the first line of each condition configuration
    # with a '-'' to enter multiple
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    service: switch.turn_on
    entity_id: switch.lounge_lights

- alias: 'Reset lights automation'
  trigger:
    platform: time
    after: '07:15:00'
  action:
    service: automation.turn_on
    entity_id: automation.lounge_lights_on_in_the_evening
